#ifndef BOWLER_AUDIO_HPP
#define BOWLER_AUDIO_HPP

//////////////////////////////////////////////////////
// DEFINES
//////////////////////////////////////////////////////

#define MUSIC_TYPE_TUPLE \
	MUSIC_TYPE_ENTRY( MUSIC_TYPE_GUI, "game\\bowler\\audio\\music\\OldeTimey" ) \
	MUSIC_TYPE_ENTRY( MUSIC_TYPE_HAMMOCK_FIGHT, "game\\bowler\\audio\\music\\HammockFight" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_BRIGHT_WISH, "game\\bowler\\audio\\music\\BrightWish" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_CIRCUS_WALTZ_FX, "game\\bowler\\audio\\music\\CircusWaltzFX" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_FRIENDLY_DAY, "game\\bowler\\audio\\music\\FriendlyDay" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_GOLD_RUSH, "game\\bowler\\audio\\music\\GoldRush" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_MERRY_GO, "game\\bowler\\audio\\music\\MerryGo" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_PLUCKY_DAISY, "game\\bowler\\audio\\music\\PluckyDaisy" ) \
    MUSIC_TYPE_ENTRY( MUSIC_TYPE_WALL_PAPER, "game\\bowler\\audio\\music\\Wallpaper" ) \


#define SOUND_TYPE_TUPLE \
	SOUND_TYPE_ENTRY( SOUND_TYPE_BUTTON_CLICK, "game\\bowler\\audio\\effects\\button_click" ) \
	SOUND_TYPE_ENTRY( SOUND_TYPE_RING, "game\\bowler\\audio\\effects\\button_click" )

#define MUSIC_LEVEL_TUPLE \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_00, MUSIC_TYPE_GUI ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_01, MUSIC_TYPE_HAMMOCK_FIGHT ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_02, MUSIC_TYPE_BRIGHT_WISH ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_03, MUSIC_TYPE_CIRCUS_WALTZ_FX ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_04, MUSIC_TYPE_FRIENDLY_DAY ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_05, MUSIC_TYPE_GOLD_RUSH ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_06, MUSIC_TYPE_MERRY_GO ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_07, MUSIC_TYPE_PLUCKY_DAISY ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_08, MUSIC_TYPE_WALL_PAPER ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_09, MUSIC_TYPE_HAMMOCK_FIGHT ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_10, MUSIC_TYPE_BRIGHT_WISH ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_11, MUSIC_TYPE_CIRCUS_WALTZ_FX ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_12, MUSIC_TYPE_FRIENDLY_DAY ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_13, MUSIC_TYPE_GOLD_RUSH ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_14, MUSIC_TYPE_MERRY_GO ) \
    MUSIC_LEVEL_TYPE_ENTRY( MUSIC_LEVEL_15, MUSIC_TYPE_PLUCKY_DAISY ) \

enum MusicType
{
#define MUSIC_TYPE_ENTRY( ENUM, FILENAME ) ENUM,
	MUSIC_TYPE_TUPLE
#undef MUSIC_TYPE_ENTRY
	MUSIC_TYPE_MAX
};

enum SoundType
{
#define SOUND_TYPE_ENTRY( ENUM, FILENAME ) ENUM,
	SOUND_TYPE_TUPLE
#undef SOUND_TYPE_ENTRY
	SOUND_TYPE_MAX
};

enum MusicLevelType
{
#define MUSIC_LEVEL_TYPE_ENTRY( ENUM, MUSIC_TYPE ) ENUM,
	MUSIC_LEVEL_TUPLE
#undef MUSIC_LEVEL_TYPE_ENTRY
	MUSIC_LEVEL_TYPE_MAX
};

#endif
